# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pho\repos\pyPhoCoreHelpers\src\pyphocorehelpers\gui\Qt\InlineFilesystemPathSelectWidget\InlineFilesystemPathSelectBase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblMain = QtWidgets.QLabel(Form)
        self.lblMain.setObjectName("lblMain")
        self.gridLayout.addWidget(self.lblMain, 0, 0, 1, 1)
        self.txtFilePath = FilesystemPathLineEdit(Form)
        self.txtFilePath.setClearButtonEnabled(True)
        self.txtFilePath.setObjectName("txtFilePath")
        self.gridLayout.addWidget(self.txtFilePath, 0, 1, 1, 1)
        self.btnSelectFile = QtWidgets.QToolButton(Form)
        self.btnSelectFile.setMinimumSize(QtCore.QSize(30, 22))
        self.btnSelectFile.setText("")
        icon = QtGui.QIcon.fromTheme("folder")
        self.btnSelectFile.setIcon(icon)
        self.btnSelectFile.setObjectName("btnSelectFile")
        self.gridLayout.addWidget(self.btnSelectFile, 0, 2, 1, 1)
        self.btnAlternate = QtWidgets.QToolButton(Form)
        self.btnAlternate.setEnabled(False)
        self.btnAlternate.setText("")
        self.btnAlternate.setArrowType(QtCore.Qt.DownArrow)
        self.btnAlternate.setObjectName("btnAlternate")
        self.gridLayout.addWidget(self.btnAlternate, 0, 3, 1, 1)
        self.gridLayout.setColumnMinimumWidth(1, 100)
        self.gridLayout.setColumnMinimumWidth(2, 30)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblMain.setText(_translate("Form", "Path"))
        self.txtFilePath.setPlaceholderText(_translate("Form", "No file selected"))
        self.btnAlternate.setToolTip(_translate("Form", "An alternative action"))
from pyphocorehelpers.gui.Qt.InlineFilesystemPathSelectWidget.FilesystemPathLineEdit import FilesystemPathLineEdit
